package com.demo.mydemo


/* loaded from: classes.dex */
object idddd {
    var AC_App_ID = "5532089"
    var AC_Banner_ID = "Banner_Android"
    var AC_Inter_ID = "Interstitial_Android"
    var AC_reward_ID = "Rewarded_Android"
    var Admob_AppOpen_ID1 = "id"
    var Admob_AppOpen_ID11 = "id"
    var Admob_AppOpen_ID2 = "id"
    var Admob_AppOpen_ID22 = "id"
    var Admob_AppOpen_ID3 = "id"
    var Admob_AppOpen_ID33 = "id"
    var Admob_App_ID = "ca-app-pub-3940256099942544~3347511713"
    var Admob_Banner_ID1 = "id"
    var Admob_Banner_ID11 = "id"
    var Admob_Banner_ID2 = "id"
    var Admob_Banner_ID22 = "id"
    var Admob_Banner_ID3 = "id"
    var Admob_Banner_ID33 = "id"
    var Admob_Inter_ID1 = "id"
    var Admob_Inter_ID11 = "id"
    var Admob_Inter_ID2 = "id"
    var Admob_Inter_ID22 = "id"
    var Admob_Inter_ID3 = "id"
    var Admob_Inter_ID33 = "id"
    var Admob_Native_ID1 = "id"
    var Admob_Native_ID11 = "id"
    var Admob_Native_ID2 = "id"
    var Admob_Native_ID22 = "id"
    var Admob_Native_ID3 = "id"
    var Admob_Native_ID33 = "id"
    var Admob_rvi_ID1 = "id"
    var Admob_rvi_ID11 = "id"
    var Admob_rvi_ID2 = "id"
    var Admob_rvi_ID22 = "id"
    var Admob_rvi_ID3 = "id"
    var Admob_rvi_ID33 = "id"
    var Ads_Link = "https://gist.githubusercontent.com/salsawo/4b2faf42ccc9589a7c9b097b8128f897/raw/getdailydiamondstips.getdiamondffffftoolstips.getfreediamond.dailydiamond.getdailydiamondstips.json"
    var FB_Banner1 = "id"
    var FB_Banner2 = "id"
    var FB_Banner3 = "id"
    var FB_Banner4 = "id"
    var FB_Banner5 = "id"
    var FB_Inter1 = "id"
    var FB_Inter2 = "id"
    var FB_Inter3 = "id"
    var FB_Inter4 = "id"
    var FB_Inter5 = "id"
    var FB_MR1 = "id"
    var FB_MR2 = "id"
    var FB_MR3 = "id"
    var FB_MR4 = "id"
    var FB_MR5 = "id"
    var FB_Native1 = "id"
    var FB_Native2 = "id"
    var FB_Native3 = "id"
    var FB_Native4 = "id"
    var FB_Native5 = "id"
    var FB_NativeSmall1 = "id"
    var FB_NativeSmall2 = "id"
    var FB_NativeSmall3 = "id"
    var FB_NativeSmall4 = "id"
    var FB_NativeSmall5 = "id"
    var Tappx = "205265073"
}